# -*- coding: utf-8 -*-
"""Assignment 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_kvBrAHLbRAQACfZm-MCVDUdL821-Xz
"""

import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense        
from tensorflow.keras.optimizers import Adam

wine_data = load_wine() 
 

print('Example data: ')
print(wine_data.data[:5])
print('Example labels: ')
print(wine_data.target[:5])

x = wine_data.data 
y_ = wine_data.target.reshape(-1, 1) 
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

print(y[:5])

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
train_x.shape, test_x.shape, train_y.shape, test_y.shape

model = Sequential()

model.add(Dense(10, input_shape=(13,), activation='relu', name='fc1'))   
model.add(Dense(10, activation='relu', name='fc2'))                             
model.add(Dense(3, activation='softmax', name='output'))                  


optimizer = Adam(lr=0.001)                                                                
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'] )

print('Neural Network Model Summary: ')
print(model.summary())

model.fit(train_x, train_y, verbose=1, batch_size=70, epochs=350)

loss, accuracy = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(loss))
print('Final test set accuracy: {:4f}'.format(accuracy))